name: Build APK
on:
  push:

jobs:
  build-apk:
    runs-on: ubuntu-24.04
    container:
      image: abrikot/dioxus-android-docker-builder:main
      volumes:
        - .:/app
#        - ./output:/app/output
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Build APK
        run: \
          ls /root/.cargo/bin
          pwd
          ls
          dx bundle --platform android
#      - name: Archive APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: apk
#          path: output