name: Build APK
on:
  push:

jobs:
  build-apk:
    runs-on: ubuntu-24.04
    container:
      image: abrikot/dioxus-android-docker-builder:main
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      - name: Build APK
        run: |
          rustup default stable
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
          dx bundle --platform android
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: target/dx/android_test/release/android/app/app/build/outputs